name: Build & Test

on:
  push:
    paths:
      - 'Makefile'
      - 'src/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake .. && make

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake .. && make && ./topic_evolution_model_test
